name: ops

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test@123"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
        
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Test@123"
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
  
  ops.api:
    image: ${DOCKER_REGISTRY-}opsapi
    build:
      context: Backend
      dockerfile: OPS.Api/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=OrderProcessing;User Id=sa;Password=Test@123;TrustServerCertificate=true"
      RabbitMq__Host: "rabbitmq"
      RabbitMq__Username: "admin"
      RabbitMq__Password: "Test@123"
    depends_on:
      - sqlserver
      - rabbitmq

  frontend:
    image: ${DOCKER_REGISTRY-}opsfrontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "${VITE_API_BASE_URL:-http://localhost:8080/api}"
    ports:
      - "5174:80"
    depends_on:
      - ops.api

volumes:
  sqldata: